apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
        sidecar.jaegertracing.io/inject: 'true'
    labels:
        app: bawling-minidouyin-user-grpc
    name: bawling-minidouyin-user-grpc
    namespace: bawling-minidouyin-user-grpc
spec:
    selector:
        matchLabels:
            name: bawling-minidouyin-user-grpc
    template:
        metadata:
            labels:
                app: bawling-minidouyin-user-grpc
                branch: dev
                version: ${BUILD_NUMBER}-${CI_COMMIT_ID}
                name: bawling-minidouyin-user-grpc
                dream-app: bawling-minidouyin-user-grpc
                dream-unit: bawling-minidouyin-user-grpc
        spec:
            imagePullSecrets:
                -   name: regcred
            containers:
                -   image: ${IMAGE}
                    imagePullPolicy: IfNotPresent
                    name: bawling-minidouyin-user-grpc
                    readinessProbe:
                        exec:
                            command: ["/bin/grpc_health_probe", "-addr=:14514"]
                        initialDelaySeconds: 5
                        periodSeconds: 5
                        successThreshold: 2
                    livenessProbe: # 如果你们有 /check_health 接口的话就加这一个段落，该接口返回 200 表示健康
                        failureThreshold: 3
                        exec:
                            command: ["/bin/grpc_health_probe", "-addr=:14514"]
                        initialDelaySeconds: 10
                        periodSeconds: 10
                        timeoutSeconds: 1
                    # I deleted the hook for that the app will capture the ctrlc signal
                    # lifecycle:
                    #     preStop:
                    #         exec:
                    #             command:
                    #                 - sleep
                    #                 - 15
                    envFrom:
                        -   configMapRef:
                                name: env-config
                        -   configMapRef:
                                name: config
                    ports:
                        -   containerPort: 14514
            terminationGracePeriodSeconds: 30
