apiVersion: v1
kind: Service
metadata:
    name: bawling-minidouyin-user-grpc
    namespace: bawling-minidouyin-user-grpc
spec:
    ports: # 自己写吧
        -   name: grpc
            port: 14514
            protocol: TCP
            targetPort: 14514
    selector:
        name: bawling-minidouyin-user-grpc
        branch: dev
    type: ClusterIP